<template><h1 id="第五課-森さんは7時に起きます" tabindex="-1"><a class="header-anchor" href="#第五課-森さんは7時に起きます" aria-hidden="true">#</a> 第五課　森さんは7時に起きます</h1>
<h4 id="动词" tabindex="-1"><a class="header-anchor" href="#动词" aria-hidden="true">#</a> 动词</h4>
<blockquote>
<p>所有动词原型都是由う段结尾</p>
</blockquote>
<ul>
<li>
<h5 id="一类动词-五段动词" tabindex="-1"><a class="header-anchor" href="#一类动词-五段动词" aria-hidden="true">#</a> 一类动词（五段动词）</h5>
<ol>
<li>结尾是う段，る以外的动词，肯定是五段动词
<ul>
<li><ruby>言<rt>い</rt></ruby>う、<ruby>立<rt>た</rt></ruby>つ、<ruby>鳴<rt>な</rt></ruby>る、<ruby>住<rt>す</rt></ruby>む、<ruby>死<rt>し</rt></ruby>ね、<ruby>飛<rt>と</rt></ruby>ぶ、<ruby>書<rt>か</rt></ruby>く。<ruby>注<rt>そそ</rt></ruby>ぐ、<ruby>押<rt>お</rt></ruby>す、</li>
<li><ruby>勝<rt>か</rt></ruby>つ、遊[^あそ]ぶ、行く</li>
</ul>
</li>
<li>「汉字+る」的汉字发音2个音阶以上
<ul>
<li>帰<code>かえ</code>る、走[^はし]る、入[^はい]る</li>
</ul>
</li>
<li>あ段+る，う段+る，お段+る
<ul>
<li>困[^こま]る、怒[^おこ]る、やる、売る、降る</li>
</ul>
</li>
<li>特例
<ul>
<li>切[^き]る、帰[^かえ]る、走[^はし]る</li>
</ul>
</li>
<li>ます形的前面一个字的母音是i
<ul>
<li>休みます、書きます、休む</li>
</ul>
</li>
</ol>
</li>
<li>
<h5 id="二类动词-一段动词" tabindex="-1"><a class="header-anchor" href="#二类动词-一段动词" aria-hidden="true">#</a> 二类动词（一段动词）</h5>
<ol>
<li>い段+る、え段+る
<ul>
<li>起きる、食べる、見る、寝る</li>
</ul>
</li>
<li>ます形的前面一个字的母音是e
<ul>
<li>寝ます、食べます</li>
</ul>
</li>
<li>「〜ます」前面的发音只有一个音阶</li>
<li><code>在</code>家<code>睡</code>觉<code>看</code>奇葩，<code>出</code>门<code>穿</code>衣<code>似</code>如花 (居る　寝る　<code>見</code>る　出る　着る　似る)</li>
</ol>
</li>
<li>
<h5 id="三类动词-サ变-カ变" tabindex="-1"><a class="header-anchor" href="#三类动词-サ变-カ变" aria-hidden="true">#</a> 三类动词（サ变/カ变）</h5>
<ol>
<li>カ变：来る　→　来ます　します　　はなさせる</li>
<li>サ变：する 勉強します</li>
</ol>
</li>
</ul>
<p>「ます」形</p>
<ol>
<li>3类动词 → 来ます、します、动词性名词します　待つ</li>
</ol>
<ul>
<li>自动词 和 他动词
<ol>
<li>自动词：强调”状态的变化“、动词前面的助词不是を</li>
<li>他动词：强调”改变状态的原因“、动词前面的助词是を</li>
</ol>
</li>
</ul>
<h4 id="动词变化" tabindex="-1"><a class="header-anchor" href="#动词变化" aria-hidden="true">#</a> 动词变化</h4>
<h5 id="第一类动词" tabindex="-1"><a class="header-anchor" href="#第一类动词" aria-hidden="true">#</a> 第一类动词</h5>
<table>
<thead>
<tr>
<th></th>
<th>会</th>
<th>書</th>
<th></th>
<th>泳</th>
<th></th>
<th>死</th>
<th></th>
<th>読</th>
<th>帰</th>
<th></th>
</tr>
</thead>
<tbody>
<tr>
<td>あ段</td>
<td>わ</td>
<td>か</td>
<td>が</td>
<td>さ</td>
<td>た</td>
<td>な</td>
<td>ば</td>
<td>ま</td>
<td>ら</td>
<td>ない(否定)・なかった・せる(使役形)・れる(受身形/尊敬形)</td>
</tr>
<tr>
<td>い段</td>
<td>い</td>
<td>き</td>
<td>ぎ</td>
<td>し</td>
<td>ち</td>
<td>に</td>
<td>び</td>
<td>み</td>
<td>り</td>
<td>ます</td>
</tr>
<tr>
<td>う段</td>
<td>う</td>
<td>く</td>
<td>ぐ</td>
<td>す</td>
<td>つ</td>
<td>ぬ</td>
<td>ぶ</td>
<td>む</td>
<td>る</td>
<td>辞書・な</td>
</tr>
<tr>
<td>え段</td>
<td>え</td>
<td>け</td>
<td>げ</td>
<td>せ</td>
<td>て</td>
<td>ね</td>
<td>べ</td>
<td>め</td>
<td>れ</td>
<td>命令形・る(可能形)・ば(条件形)</td>
</tr>
<tr>
<td>お段</td>
<td>お</td>
<td>こ</td>
<td>ご</td>
<td>そ</td>
<td>と</td>
<td>の</td>
<td>ぼ</td>
<td>も</td>
<td>ろ</td>
<td>う(意向形)</td>
</tr>
<tr>
<td>音便</td>
<td>っ</td>
<td>い</td>
<td>い</td>
<td>し</td>
<td>っ</td>
<td>ん</td>
<td>ん</td>
<td>ん</td>
<td>ん</td>
<td>て(で)・た(だ）</td>
</tr>
<tr>
<td></td>
<td></td>
<td></td>
<td>で・だ</td>
<td></td>
<td></td>
<td>で・だ</td>
<td>で・だ</td>
<td>で・だ</td>
<td></td>
<td></td>
</tr>
</tbody>
</table>
<table>
<thead>
<tr>
<th>おととい</th>
<th>昨日きのう</th>
<th>今日きょう</th>
<th>明日あした</th>
<th>明後日あさって</th>
<th>毎日まいにち</th>
</tr>
</thead>
<tbody>
<tr>
<td></td>
<td></td>
<td><strong>今朝</strong>けさ</td>
<td></td>
<td></td>
<td>毎朝まいあさ</td>
</tr>
<tr>
<td></td>
<td><strong>夕べ</strong></td>
<td><strong>今晩</strong>こんばん</td>
<td></td>
<td></td>
<td>毎晩まいばん</td>
</tr>
<tr>
<td>先々週</td>
<td>先週せんしゅう</td>
<td>今週こんしゅう</td>
<td>来週らいしゅう</td>
<td>再来週さらいしゅう</td>
<td>毎週まいしゅう</td>
</tr>
<tr>
<td>先々月</td>
<td>先月</td>
<td>今月</td>
<td>来月</td>
<td>再来月</td>
<td><strong>毎月</strong>まいつき</td>
</tr>
<tr>
<td><strong>おととし</strong></td>
<td><strong>去年</strong>きょねん</td>
<td><strong>今年</strong>ことし</td>
<td>来年</td>
<td>再来年</td>
<td><strong>毎年</strong>まいとし</td>
</tr>
</tbody>
</table>
<table>
<thead>
<tr>
<th>一時</th>
<th>いちじ</th>
<th>七時</th>
<th>しちじ</th>
</tr>
</thead>
<tbody>
<tr>
<td>二時</td>
<td>にじ</td>
<td>八時</td>
<td>はちじ</td>
</tr>
<tr>
<td>三時</td>
<td>さんじ</td>
<td>九時</td>
<td>くじ</td>
</tr>
<tr>
<td>四時</td>
<td>よじ</td>
<td>十時</td>
<td>じゅうじ</td>
</tr>
<tr>
<td>五時</td>
<td>ごじ</td>
<td>十一時</td>
<td>じゅういちじ</td>
</tr>
<tr>
<td>六時</td>
<td>ろくじ</td>
<td>十二時</td>
<td>じゅうにじ</td>
</tr>
<tr>
<td>0時</td>
<td>れいじ</td>
<td>何時</td>
<td>なんじ</td>
</tr>
</tbody>
</table>
<h4 id="语法" tabindex="-1"><a class="header-anchor" href="#语法" aria-hidden="true">#</a> 语法</h4>
<ol>
<li>
<h5 id="森さんは七時に起きます" tabindex="-1"><a class="header-anchor" href="#森さんは七時に起きます" aria-hidden="true">#</a> 森さんは七時に起きます</h5>
<p>に<code>动作发生</code>的时间<code>点</code></p>
<p>有具体数字时加に，没有具体数字不加に</p>
<p>有具体日子的节假日加に</p>
<p>星期可加可不加に</p>
<p>时间后面有ごろ的时候，可以省略に</p>
<ul>
<li>今晩何時に寝ますか</li>
</ul>
</li>
<li>
<h5 id="〜から-from〜-时间空间起点、-〜まで-to〜-时间空间的终点" tabindex="-1"><a class="header-anchor" href="#〜から-from〜-时间空间起点、-〜まで-to〜-时间空间的终点" aria-hidden="true">#</a> 〜から　from〜 时间空间起点、 〜まで　to〜 时间空间的终点</h5>
<ul>
<li>
<p>私は毎日１０：３０から勉強します</p>
</li>
<li>
<p>旅行は水曜日までです</p>
</li>
</ul>
<blockquote>
<p>5時<u>から</u>＝5時<u>に始まります</u></p>
<p>5時<u>まで</u>＝5時<u>に終わります</u></p>
<p>11時に寝ます≠11時まで寝ます → 睡到11点</p>
<p>11時に寝ます≈11時から寝ます → 从11点睡觉</p>
</blockquote>
</li>
<li>
<h5 id="何時に-始まりますか-ーー10時に始まります" tabindex="-1"><a class="header-anchor" href="#何時に-始まりますか-ーー10時に始まります" aria-hidden="true">#</a> 何時に　始まりますか　ーー10時に始まります</h5>
<h5 id="いつ-始まりますか-什么时候-具体日子-ーー十二月に始まります-ーー来月始まります" tabindex="-1"><a class="header-anchor" href="#いつ-始まりますか-什么时候-具体日子-ーー十二月に始まります-ーー来月始まります" aria-hidden="true">#</a> いつ　始まりますか<code>（什么时候，具体日子）</code>　ーー十二月に始まります　ーー来月始まります</h5>
</li>
</ol>
<p>き</p>
<p><ruby>今<rt>いま</rt></ruby></p>
<p><ruby>午後<rt>ごご</rt></ruby></p>
<p><ruby>午前<rt>ごぜん</rt></ruby></p>
<p>朝　あさ</p>
<p>夜　よる　夜里，夜，晚上，时间从晚上一直到深夜</p>
<p>晩　ばん　晚上，时间不包括深夜</p>
<p>昨日の朝は</p>
</template>
